name: Build Tweak
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Tweak
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git theos
          
      - name: Setup iOS SDK
        run: |
          git clone https://github.com/theos/sdks.git theos/sdks

      - name: Build
        run: |
          export THEOS=${GITHUB_WORKSPACE}/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RegramBypass_dylib
          path: .theos/obj/debug/RegramBypass.dylib
